# syntax = docker/dockerfile:1.3
# Build and compile the webapp
FROM node:16-alpine

# Env from args 
ARG TURBO_TEAM
ARG TURBO_TOKEN
ENV TURBO_TEAM=$TURBO_TEAM
ENV TURBO_TOKEN=$TURBO_TOKEN

WORKDIR /app

# Install pnpm 
RUN apk add --update curl && rm -rf /var/cache/apk/*
RUN npm install -g pnpm@7.1

# Install packages
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY ui/package.json ./ui/package.json
COPY web/package.json ./web/package.json

RUN pnpm install --shamefully-hoist --strict-peer-dependencies=false --frozen-lockfile --ignore-scripts=true --filter=web...

COPY ./* ./
COPY ./web ./web
COPY ./ui ./ui

# Disable telemetry
RUN pnpm run --filter=web telemetry:disable 

# Run build with secrets
RUN --mount=type=secret,id=_env,dst=/app/.env pnpm run --filter=web db push \
  && pnpm run --filter=web seed \
  && pnpm run build

CMD ["./copy-env.sh && pnpm", "run", "start:web"]
