version: '3.1'

services:
    typesense:
        image: typesense/typesense:0.24.0
        environment:
            TYPESENSE_API_KEY: typesense
            TYPESENSE_DATA_DIR: /data
        volumes:
            - search-data:/data
        ports:
            - 7700:8108

    db:
        image: postgres:12-alpine
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: locaci_db
        ports:
            - '5432:5432'

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

    # quirrel:
    #     image: ghcr.io/quirrel-dev/quirrel:main
    #     environment:
    #         REDIS_URL: redis://redis:6379
    #         PASSPHRASES: quirrel
    #     ports:
    #         - '9181:9181'

    redis:
        image: redis
        environment:
            - REDIS_PASSWORD=redis_password
        command: >
            redis-server --requirepass redis_password
        ports:
            - '6379:6379'

    redis-gui:
        image: rediscommander/redis-commander
        environment:
            - REDIS_HOSTS=local:redis:6379:0:redis_password
        ports:
            - '8089:8081'
    openstreetmap-search:
        image: mediagis/nominatim:4.1
        restart: always
        ports:
            - '8088:8080'
        environment:
            # To restrict search data to ivory coast
            PBF_URL: https://download.geofabrik.de/africa/ivory-coast-latest.osm.pbf
            NOMINATIM_PASSWORD: password
        volumes:
            - osm-search-data:/var/lib/postgresql/14/main
        shm_size: 1gb

volumes:
    osm-search-data:
    search-data:
        driver: local
    db-data:
        driver: local
