version: '3.1'

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: locaci_db
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  quirrel:
    image: ghcr.io/quirrel-dev/quirrel:main
    environment:
      REDIS_URL: redis://redis:6379
      PASSPHRASES: quirrel
    ports:
      - '9181:9181'

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

  redis-gui:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8089:8081'
volumes:
  redis_data:
  db-data:
    driver: local