@startuml "locaci architecture"

left to right direction

:User: as user

package "services externes" {
    database "Base de données" {
        [PostgreSQL] as db
    }

    [Service d'envoi SMS] as twilio
    [Service d'alerte d'erreurs] as alerting
    [Service de signature PDF] as pdfsign
}
package "Serveur OVH" as server {
    node loadbalancer as lb {
        [web] as web
    }

    node "Services internes" as internal  {
        [Message Queue] as redis
        [Systeme de Recherche] as typesense
        [Collection d'analytics] as analytics
    }

    node "Services parralelles" as threads {
        [Indexeur de Recherche] as indexer
        [Gestionnaire de notifications] as notificator
    }

    [Serveur web] as nginx


    web <-down-> db
    web -down-> pdfsign : "Signature Contrat de bail & Etat des lieux"
    web -down-> alerting : Envoie les erreurs
    
    web -down-> redis : "Envoi tâches"
    web -down-> typesense : "Recherche"
    web --> analytics : Envoie les données utilisateurs
    
    redis -up-> indexer  : Exécute l'indexation
    redis -up-> notificator  : Envoie les notifications
    indexer -up-> typesense : Indexe les documents
    
    notificator -down-> twilio : Envoi de SMS
}




' Relations
nginx <-up-> user
nginx <-down-> web


@enduml